package com.phy0312.shopassistant.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MAIN_ITEM.
 */
public class MainItem {

    private Long id;
    private String WeekRecommends;
    private String Coupons;
    private String HuoDongs;
    private Long Flims;

    public MainItem() {
    }

    public MainItem(Long id) {
        this.id = id;
    }

    public MainItem(Long id, String WeekRecommends, String Coupons, String HuoDongs, Long Flims) {
        this.id = id;
        this.WeekRecommends = WeekRecommends;
        this.Coupons = Coupons;
        this.HuoDongs = HuoDongs;
        this.Flims = Flims;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWeekRecommends() {
        return WeekRecommends;
    }

    public void setWeekRecommends(String WeekRecommends) {
        this.WeekRecommends = WeekRecommends;
    }

    public String getCoupons() {
        return Coupons;
    }

    public void setCoupons(String Coupons) {
        this.Coupons = Coupons;
    }

    public String getHuoDongs() {
        return HuoDongs;
    }

    public void setHuoDongs(String HuoDongs) {
        this.HuoDongs = HuoDongs;
    }

    public Long getFlims() {
        return Flims;
    }

    public void setFlims(Long Flims) {
        this.Flims = Flims;
    }

}
