package com.phy0312.shopassistant.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAZA.
 */
public class Plaza {

    private Long id;
    private String CityId;
    private java.util.Date CreateTime;
    private Double Latitude;
    private Double Longitude;
    /** Not-null value. */
    private String Name;
    private String PinYin;
    /** Not-null value. */
    private String PlazaId;
    private String Address;
    private String phone;
    private Integer Type;

    public Plaza() {
    }

    public Plaza(Long id) {
        this.id = id;
    }

    public Plaza(Long id, String CityId, java.util.Date CreateTime, Double Latitude, Double Longitude, String Name, String PinYin, String PlazaId, String Address, String phone, Integer Type) {
        this.id = id;
        this.CityId = CityId;
        this.CreateTime = CreateTime;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.Name = Name;
        this.PinYin = PinYin;
        this.PlazaId = PlazaId;
        this.Address = Address;
        this.phone = phone;
        this.Type = Type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCityId() {
        return CityId;
    }

    public void setCityId(String CityId) {
        this.CityId = CityId;
    }

    public java.util.Date getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(java.util.Date CreateTime) {
        this.CreateTime = CreateTime;
    }

    public Double getLatitude() {
        return Latitude;
    }

    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    public Double getLongitude() {
        return Longitude;
    }

    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPinYin() {
        return PinYin;
    }

    public void setPinYin(String PinYin) {
        this.PinYin = PinYin;
    }

    /** Not-null value. */
    public String getPlazaId() {
        return PlazaId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlazaId(String PlazaId) {
        this.PlazaId = PlazaId;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

}
