package com.phy0312.shopassistant.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;

/**
 * Entity mapped to table COUPON.
 */
public class Coupon implements Parcelable{

    private Long id;
    private String CouponId;
    private String StoreId;
    private String Name;
    private Long StartTime;
    private Long EndTime;
    private Integer Category;
    private String Description;
    private String iconPath;
    private java.util.Date CreateTime;
    private int count;

    public Coupon() {
    }

    public Coupon(Long id) {
        this.id = id;
    }

    public Coupon(Long id, String CouponId, String StoreId, String Name, Long StartTime, Long EndTime,
                  Integer Category, String Description,
                  java.util.Date CreateTime,
                  String iconPath, int count) {
        this.id = id;
        this.CouponId = CouponId;
        this.StoreId = StoreId;
        this.Name = Name;
        this.StartTime = StartTime;
        this.EndTime = EndTime;
        this.Category = Category;
        this.Description = Description;
        this.CreateTime = CreateTime;
        this.iconPath = iconPath;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCouponId() {
        return CouponId;
    }

    public void setCouponId(String CouponId) {
        this.CouponId = CouponId;
    }

    public String getStoreId() {
        return StoreId;
    }

    public void setStoreId(String StoreId) {
        this.StoreId = StoreId;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Long getStartTime() {
        return StartTime;
    }

    public void setStartTime(Long StartTime) {
        this.StartTime = StartTime;
    }

    public Long getEndTime() {
        return EndTime;
    }

    public void setEndTime(Long EndTime) {
        this.EndTime = EndTime;
    }

    public Integer getCategory() {
        return Category;
    }

    public void setCategory(Integer Category) {
        this.Category = Category;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public java.util.Date getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(java.util.Date CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getIconPath() {
        return iconPath;
    }

    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }


    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.CouponId);
        dest.writeString(this.StoreId);
        dest.writeString(this.Name);
        dest.writeValue(this.StartTime);
        dest.writeValue(this.EndTime);
        dest.writeValue(this.Category);
        dest.writeString(this.Description);
        dest.writeString(this.iconPath);
        dest.writeLong(CreateTime != null ? CreateTime.getTime() : -1);
        dest.writeInt(this.count);
    }

    private Coupon(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.CouponId = in.readString();
        this.StoreId = in.readString();
        this.Name = in.readString();
        this.StartTime = (Long) in.readValue(Long.class.getClassLoader());
        this.EndTime = (Long) in.readValue(Long.class.getClassLoader());
        this.Category = (Integer) in.readValue(Integer.class.getClassLoader());
        this.Description = in.readString();
        this.iconPath = in.readString();
        long tmpCreateTime = in.readLong();
        this.CreateTime = tmpCreateTime == -1 ? null : new Date(tmpCreateTime);
        this.count = in.readInt();
    }

    public static final Creator<Coupon> CREATOR = new Creator<Coupon>() {
        public Coupon createFromParcel(Parcel source) {
            return new Coupon(source);
        }

        public Coupon[] newArray(int size) {
            return new Coupon[size];
        }
    };
}
