package com.phy0312.shopassistant.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.phy0312.shopassistant.db.Coupon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table COUPON.
*/
public class CouponDao extends AbstractDao<Coupon, Long> {

    public static final String TABLENAME = "COUPON";

    /**
     * Properties of entity Coupon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CouponId = new Property(1, String.class, "CouponId", false, "COUPON_ID");
        public final static Property StoreId = new Property(2, String.class, "StoreId", false, "STORE_ID");
        public final static Property Name = new Property(3, String.class, "Name", false, "NAME");
        public final static Property StartTime = new Property(4, Long.class, "StartTime", false, "START_TIME");
        public final static Property EndTime = new Property(5, Long.class, "EndTime", false, "END_TIME");
        public final static Property Category = new Property(6, Integer.class, "Category", false, "CATEGORY");
        public final static Property Description = new Property(7, String.class, "Description", false, "DESCRIPTION");
        public final static Property CreateTime = new Property(8, java.util.Date.class, "CreateTime", false, "CREATE_TIME");
    };


    public CouponDao(DaoConfig config) {
        super(config);
    }
    
    public CouponDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'COUPON' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'COUPON_ID' TEXT," + // 1: CouponId
                "'STORE_ID' TEXT," + // 2: StoreId
                "'NAME' TEXT," + // 3: Name
                "'START_TIME' INTEGER," + // 4: StartTime
                "'END_TIME' INTEGER," + // 5: EndTime
                "'CATEGORY' INTEGER," + // 6: Category
                "'DESCRIPTION' TEXT," + // 7: Description
                "'CREATE_TIME' INTEGER);"); // 8: CreateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'COUPON'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Coupon entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String CouponId = entity.getCouponId();
        if (CouponId != null) {
            stmt.bindString(2, CouponId);
        }
 
        String StoreId = entity.getStoreId();
        if (StoreId != null) {
            stmt.bindString(3, StoreId);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(4, Name);
        }
 
        Long StartTime = entity.getStartTime();
        if (StartTime != null) {
            stmt.bindLong(5, StartTime);
        }
 
        Long EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindLong(6, EndTime);
        }
 
        Integer Category = entity.getCategory();
        if (Category != null) {
            stmt.bindLong(7, Category);
        }
 
        String Description = entity.getDescription();
        if (Description != null) {
            stmt.bindString(8, Description);
        }
 
        java.util.Date CreateTime = entity.getCreateTime();
        if (CreateTime != null) {
            stmt.bindLong(9, CreateTime.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Coupon readEntity(Cursor cursor, int offset) {
        Coupon entity = new Coupon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // CouponId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // StoreId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Name
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // StartTime
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // EndTime
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // Category
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Description
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // CreateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Coupon entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCouponId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStoreId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStartTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setEndTime(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setCategory(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setDescription(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreateTime(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Coupon entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Coupon entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
