package com.phy0312.shopassistant.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.phy0312.shopassistant.db.Plaza;
import com.phy0312.shopassistant.db.Store;
import com.phy0312.shopassistant.db.HuoDong;
import com.phy0312.shopassistant.db.Coupon;
import com.phy0312.shopassistant.db.MainItem;

import com.phy0312.shopassistant.db.PlazaDao;
import com.phy0312.shopassistant.db.StoreDao;
import com.phy0312.shopassistant.db.HuoDongDao;
import com.phy0312.shopassistant.db.CouponDao;
import com.phy0312.shopassistant.db.MainItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig plazaDaoConfig;
    private final DaoConfig storeDaoConfig;
    private final DaoConfig huoDongDaoConfig;
    private final DaoConfig couponDaoConfig;
    private final DaoConfig mainItemDaoConfig;

    private final PlazaDao plazaDao;
    private final StoreDao storeDao;
    private final HuoDongDao huoDongDao;
    private final CouponDao couponDao;
    private final MainItemDao mainItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        plazaDaoConfig = daoConfigMap.get(PlazaDao.class).clone();
        plazaDaoConfig.initIdentityScope(type);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        huoDongDaoConfig = daoConfigMap.get(HuoDongDao.class).clone();
        huoDongDaoConfig.initIdentityScope(type);

        couponDaoConfig = daoConfigMap.get(CouponDao.class).clone();
        couponDaoConfig.initIdentityScope(type);

        mainItemDaoConfig = daoConfigMap.get(MainItemDao.class).clone();
        mainItemDaoConfig.initIdentityScope(type);

        plazaDao = new PlazaDao(plazaDaoConfig, this);
        storeDao = new StoreDao(storeDaoConfig, this);
        huoDongDao = new HuoDongDao(huoDongDaoConfig, this);
        couponDao = new CouponDao(couponDaoConfig, this);
        mainItemDao = new MainItemDao(mainItemDaoConfig, this);

        registerDao(Plaza.class, plazaDao);
        registerDao(Store.class, storeDao);
        registerDao(HuoDong.class, huoDongDao);
        registerDao(Coupon.class, couponDao);
        registerDao(MainItem.class, mainItemDao);
    }
    
    public void clear() {
        plazaDaoConfig.getIdentityScope().clear();
        storeDaoConfig.getIdentityScope().clear();
        huoDongDaoConfig.getIdentityScope().clear();
        couponDaoConfig.getIdentityScope().clear();
        mainItemDaoConfig.getIdentityScope().clear();
    }

    public PlazaDao getPlazaDao() {
        return plazaDao;
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

    public HuoDongDao getHuoDongDao() {
        return huoDongDao;
    }

    public CouponDao getCouponDao() {
        return couponDao;
    }

    public MainItemDao getMainItemDao() {
        return mainItemDao;
    }

}
