package com.phy0312.shopassistant.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HUO_DONG.
 */
public class HuoDong {

    private Long id;
    private String HuoDongId;
    private String StoreId;
    private Long StartTime;
    private Long EndTime;
    private Integer Category;
    private String Description;
    private String Name;
    private String Icon;
    private Integer Status;
    private java.util.Date CreateTime;

    public HuoDong() {
    }

    public HuoDong(Long id) {
        this.id = id;
    }


    public HuoDong(Long id, String huoDongId, String storeId, Long startTime, Long endTime, Integer category, String description, String name, String icon, Integer status) {
        this.id = id;
        HuoDongId = huoDongId;
        StoreId = storeId;
        StartTime = startTime;
        EndTime = endTime;
        Category = category;
        Description = description;
        Name = name;
        Icon = icon;
        Status = status;
    }

    public HuoDong(Long id, String HuoDongId, String StoreId, Long StartTime, Long EndTime, Integer Category, String Description, String Name, String Icon, Integer Status, java.util.Date CreateTime) {
        this.id = id;
        this.HuoDongId = HuoDongId;
        this.StoreId = StoreId;
        this.StartTime = StartTime;
        this.EndTime = EndTime;
        this.Category = Category;
        this.Description = Description;
        this.Name = Name;
        this.Icon = Icon;
        this.Status = Status;
        this.CreateTime = CreateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHuoDongId() {
        return HuoDongId;
    }

    public void setHuoDongId(String HuoDongId) {
        this.HuoDongId = HuoDongId;
    }

    public String getStoreId() {
        return StoreId;
    }

    public void setStoreId(String StoreId) {
        this.StoreId = StoreId;
    }

    public Long getStartTime() {
        return StartTime;
    }

    public void setStartTime(Long StartTime) {
        this.StartTime = StartTime;
    }

    public Long getEndTime() {
        return EndTime;
    }

    public void setEndTime(Long EndTime) {
        this.EndTime = EndTime;
    }

    public Integer getCategory() {
        return Category;
    }

    public void setCategory(Integer Category) {
        this.Category = Category;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getIcon() {
        return Icon;
    }

    public void setIcon(String Icon) {
        this.Icon = Icon;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public java.util.Date getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(java.util.Date CreateTime) {
        this.CreateTime = CreateTime;
    }

}
