package com.phy0312.shopassistant.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STORE.
 */
public class Store {

    private Long id;
    private String StoreId;
    private String PlazaId;
    private Integer Category;
    private String Name;
    private String Address;
    private Integer AverageCost;
    private String Icon;
    private String Telephone;
    private Integer Floor;
    private Integer Status;
    private java.util.Date CreateTime;
    private String Description;

    public Store() {
    }

    public Store(Long id) {
        this.id = id;
    }

    public Store(Long id, String StoreId, String PlazaId, Integer Category, String Name, String Address, Integer AverageCost, String Icon, String Telephone, Integer Floor, Integer Status, java.util.Date CreateTime, String Description) {
        this.id = id;
        this.StoreId = StoreId;
        this.PlazaId = PlazaId;
        this.Category = Category;
        this.Name = Name;
        this.Address = Address;
        this.AverageCost = AverageCost;
        this.Icon = Icon;
        this.Telephone = Telephone;
        this.Floor = Floor;
        this.Status = Status;
        this.CreateTime = CreateTime;
        this.Description = Description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStoreId() {
        return StoreId;
    }

    public void setStoreId(String StoreId) {
        this.StoreId = StoreId;
    }

    public String getPlazaId() {
        return PlazaId;
    }

    public void setPlazaId(String PlazaId) {
        this.PlazaId = PlazaId;
    }

    public Integer getCategory() {
        return Category;
    }

    public void setCategory(Integer Category) {
        this.Category = Category;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public Integer getAverageCost() {
        return AverageCost;
    }

    public void setAverageCost(Integer AverageCost) {
        this.AverageCost = AverageCost;
    }

    public String getIcon() {
        return Icon;
    }

    public void setIcon(String Icon) {
        this.Icon = Icon;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

    public Integer getFloor() {
        return Floor;
    }

    public void setFloor(Integer Floor) {
        this.Floor = Floor;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public java.util.Date getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(java.util.Date CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

}
